spring.application.name=orderFlow
server.port=8090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/orderflow_db
spring.datasource.username=orderflow_user
spring.datasource.password=orderflow_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.docker.compose.lifecycle-management=start_only


# ===== STRIPE =====
stripe.api.key=${STRIPE_API_KEY}
